FROM node:20.17

WORKDIR /workdir/app/frontend

# install stage
COPY package-lock.json package-lock.json
COPY package.json package.json
RUN npm ci --legacy-peer-deps

# run
EXPOSE 3000
CMD [ "npm", "run", "dev" ]
